services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    depends_on:
      - db
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
